### PR TITLE
Implementation of Folder structure

### PR DESCRIPTION
**Pull request by AyonPal**

### CODE REVIEW

**Review by AsishRaju — COMMENTED** [review]
hey @AyonPal  , could you explain the working of /add/folder api controller i am unable to get my head around it , and it would be a + if you could explain how your searching for files and folder in /list/folder .

Thanks !

**Comment by ghost** [comment]
Hey, @AsishRaju I had implemented the same thing in a completely different way, instead of actually storing nested folder structure in Minio, we can store all files in a single folder on the Minio, from the backend side we can fetch them directly thorough URLs, so in my approach, all folders and files stored in a random way like a tree structure, we use BFS algorithm which works recursively per single request to fetch nested folders by queueing next neighbour folders, On the database, all the folders in saved one collection, and all files saved in one collection, nested files/folders point to nested files/folders, we use those pointers to search in the collection. From frontend, we can use the store, to gives a nested kinda look in URL. I think it is the most efficient way to access folders. the source was ready I would like to add tests to it, so I can pull request once it clears all tests cases, meanwhile, you can go through it, from my GitHub Repo https://github.com/akashmrc98/canvasboard-backend

**Comment by AyonPal** [comment]
@AsishRaju every user has 2 array in db in user collection. That store root folders and root files. The root folder array stores basically the objectid of the collection table folderObjects. And root files stores the files user save on root as string. And folderObjects can store more folders recursively.

Now add/folder api takes a base path to add a folder. All folder are virtual and doesn't store on minio(only exist on db). Base path is the parent folder (can be root or any subsequent folder) and create a folder in folderObjects. And to upload files in folder you have to supply same parent folder name in upload/file.

list/folder just list folders and files in a folder (root or any subsequent folder) this kind of work like a file browser not a file system tree preview.

As for search i haven't implemented yet. What need to searched anyway?

**Comment by AyonPal** [comment]
@akashmrc98 i check your work. Your code nearly works the same way😀. The only difference is in root folder. You store root folder in minio i store in userschema.

**Comment by ghost** [comment]
@AyonPal @AsishRaju  I'm glad we are on the same page, I would like to explain it in detail, that would be great, let's have a discussion about it, because I want to show in graphically way! then we discuss the pros and cons of our work. ping me when you are free.

**Comment by AyonPal** [comment]
@akashmrc98 that will be great.

**Comment by ghost** [comment]
> @akashmrc98 that will be great.

yeah! 😀 
just ping me when you are free!
we use google meet!

**Comment by AyonPal** [comment]
Please contact in irc

**Comment by ghost** [comment]
Hey @AyonPal, I had rewritten logic from the ground once again in an asynchronous way, all required CRUD queries are finished, I need your help to add Minio server when a user creates file it should be saved in Minio server with its id, file URL should be saved in file model and the file should be uploaded to Minio server, I commented in /src/controllers/file/createFile.js. with your help, we can rewrite the createFile.js controller. Thanks

**Comment by AyonPal** [comment]
Ok im here to help. Where is the file?

**Comment by ghost** [comment]
@AyonPal here's the file [createFile.js](https://github.com/akashmrc98/canvasboard-backend/blob/master/APIs/controllers/file/createFile.js) 

And also I add postman docs, to explain how to work with API.
So can you guide me through Minio, I'm having experience with docker but I don't understand, how to run Minio inside a docker container, And I'm fascinated to learn how Minio works, and guide me with the config file. Thank you!

1)How to work with config file
On Docker, it is running fine!

**Comment by AyonPal** [comment]
Use this to install minio on sperate docker 
```bash
docker run -p 9000:9000 \
  -e "MINIO_ACCESS_KEY=minio" \
  -e "MINIO_SECRET_KEY=miniostorage" \
  minio/minio server /data
```

Then make sure make sure  docker is accessable from `localhost:9000`. Login using `ACCESS: minio`, `SECRET: minoistorage`. Then **create a bucket** named `files`.

After that you can use minio from JS API. Check [Minio JS API Docs](https://docs.min.io/docs/javascript-client-api-reference.html)

**Comment by ghost** [comment]
@AyonPal Thanks! The backend setup was done, now I understood how Minio works, I add to the required logic to save the file in Minio, I'll be writing few test cases and some code refactoring then I'll pull a request.

**Comment by AyonPal** [comment]
Ok tell me it any help needed @akashmrc98

**Pull request closed without merging**
