### PR TITLE
#8 generate unique url for sharing files

### PR DESCRIPTION
**Pull request by AyonPal**
This PR resolves:
1. Share and get unique link of a file by user.
2. Show List of Files already Shared by current user.
3. Unique link serves the shared files directly.

### CODE REVIEW

**Comment by AsishRaju** [comment]
@AyonPal  thanks for the PR 👍🏻 ,  had a doubt on  `/share/file` API: In the catch part you're checking if that shared object is already there in `sharedFiles` collection or not if available your sending response by finding that object from `sharedFiles` collection to frontend; Correct me if I am wrong. if that's the case I don't think there is a need for `/share/sharedlist`  , i would love to know the use of this API.

Looking Forward to your reply ✌🏻

**Comment by AyonPal** [comment]
@AsishRaju yes, share/file works exactly like that. share/sharedlist returns all shared files already shared by user.

**Comment by AsishRaju** [comment]
@AyonPal  any use case for 'share/sharedlist' because the user will get the link nonetheless he has already made a req for sharing the file from  `/share/file` API.

**Comment by AyonPal** [comment]
@AsishRaju its the reference for user if they want to list all files shared by them or they want to modify or delete the file already shared.

**Comment by AsishRaju** [comment]
@AyonPal  ok, seems practical reason.
One more thing whenever new API's are added, documentation of the API would be great, refer the API DOCS present [here](https://github.com/Canvasbird/canvasboard-backend#running-backend) to get started with the documentation. 
The sample doc can be found here `/APIs/apiDocs/`

**Will merge and close this PR**
Your contribution means a lot ✌🏻
#ThanksTober

**Review by AsishRaju — APPROVED** [review]

**Comment by AyonPal** [comment]
@AsishRaju ,  So its postman collection. I will update that.
Anyway can you please add this pr label `hacktoberfest-accepted`.

Thank you

**Comment by goliakshay357** [comment]
@all-contributors please add @AyonPal for code

**Pull request merged**
